import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class CreateDB {
    protected void createTables() throws SQLException {
        Connection connection = DriverManager.getConnection("jdbc:derby:CinemaDB; create=true");
        PreparedStatement tableHalls = connection.prepareStatement("CREATE TABLE HALLS (" +
                "NUM INT NOT NULL PRIMARY KEY, " +
                "NROWS INT NOT NULL)");
        tableHalls.execute();

        PreparedStatement tableSeances = connection.prepareStatement("CREATE TABLE SEANCES (" +
                "ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY," +
                " STIME VARCHAR (5) NOT NULL," +
                " FILM VARCHAR (15) NOT NULL," +
                " HALL INT NOT NULL," +
                " AGE INT NOT NULL," +
                " PRICE INT NOT NULL," +
                " FOREIGN KEY (HALL) REFERENCES HALLS (NUM))");
        tableSeances.execute();

        PreparedStatement tableReservation = connection.prepareStatement("CREATE TABLE RESERVATION (" +
                "USERID INT NOT NULL, " +
                "HROWS INT NOT NULL, " +
                "SEAT INT NOT NULL, " +
                "SEANCES INT NOT NULL, " +
                "FOREIGN KEY (SEANCES) REFERENCES SEANCES (ID))");
        tableReservation.execute();

        PreparedStatement tableRows = connection.prepareStatement("CREATE TABLE HROWS(" +
                "HALL INT NOT NULL," +
                "NROWS INT NOT NULL," +
                "SEATS INT NOT NULL)");
        tableRows.execute();
    }
}
